-- UID 컬럼들을 CHAR(26) -> VARCHAR(26)로 통일

ALTER TABLE account
    MODIFY COLUMN uid VARCHAR(26) NOT NULL;

ALTER TABLE person
    MODIFY COLUMN uid VARCHAR(26) NOT NULL;

ALTER TABLE event
    MODIFY COLUMN uid VARCHAR(26) NOT NULL;

ALTER TABLE invitation
    MODIFY COLUMN uid VARCHAR(26) NOT NULL;
